ERROR - 2021-05-15 14:20:18 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2021-05-15 14:20:18 --> Unable to connect to the database.
#0 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `orders`...', Array, false)
#2 D:\xampp\htdocs\diancan\app\Models\Orders_model.php(514): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\diancan\app\Controllers\Admin\Dashboard.php(15): App\Models\Orders_model->getOrdersCountGroupByRegion()
#4 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(876): App\Controllers\Admin\Dashboard->index()
#5 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(411): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Dashboard))
#6 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(322): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\diancan\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-05-15 14:20:18 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\xampp\\htdocs...', 100, Array)
#1 D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Admin\Dashboard), true)
#2 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('D:\\xampp\\htdocs...')
#3 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-05-15 14:20:24 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2021-05-15 14:20:24 --> Unable to connect to the database.
#0 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `orders`...', Array, false)
#2 D:\xampp\htdocs\diancan\app\Models\Orders_model.php(514): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\diancan\app\Controllers\Admin\Dashboard.php(15): App\Models\Orders_model->getOrdersCountGroupByRegion()
#4 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(876): App\Controllers\Admin\Dashboard->index()
#5 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(411): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Dashboard))
#6 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(322): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\diancan\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-05-15 14:20:24 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\xampp\\htdocs...', 100, Array)
#1 D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Admin\Dashboard), true)
#2 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('D:\\xampp\\htdocs...')
#3 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-05-15 14:23:40 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2021-05-15 14:23:40 --> Unable to connect to the database.
#0 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `orders`...', Array, false)
#2 D:\xampp\htdocs\diancan\app\Models\Orders_model.php(514): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\diancan\app\Controllers\Admin\Dashboard.php(15): App\Models\Orders_model->getOrdersCountGroupByRegion()
#4 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(876): App\Controllers\Admin\Dashboard->index()
#5 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(411): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Dashboard))
#6 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(322): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\diancan\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-05-15 14:23:40 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\xampp\\htdocs...', 100, Array)
#1 D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Admin\Dashboard), true)
#2 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('D:\\xampp\\htdocs...')
#3 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-05-15 14:24:17 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2021-05-15 14:24:17 --> Unable to connect to the database.
#0 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `orders`...', Array, false)
#2 D:\xampp\htdocs\diancan\app\Models\Orders_model.php(514): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\diancan\app\Controllers\Admin\Dashboard.php(15): App\Models\Orders_model->getOrdersCountGroupByRegion()
#4 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(876): App\Controllers\Admin\Dashboard->index()
#5 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(411): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Dashboard))
#6 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(322): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\diancan\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-05-15 14:24:17 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\xampp\\htdocs...', 100, Array)
#1 D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Admin\Dashboard), true)
#2 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('D:\\xampp\\htdocs...')
#3 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-05-15 14:24:31 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2021-05-15 14:24:31 --> Unable to connect to the database.
#0 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `orders`...', Array, false)
#2 D:\xampp\htdocs\diancan\app\Models\Orders_model.php(514): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\diancan\app\Controllers\Admin\Dashboard.php(15): App\Models\Orders_model->getOrdersCountGroupByRegion()
#4 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(876): App\Controllers\Admin\Dashboard->index()
#5 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(411): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Dashboard))
#6 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(322): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\diancan\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-05-15 14:24:31 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\xampp\\htdocs...', 100, Array)
#1 D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Admin\Dashboard), true)
#2 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('D:\\xampp\\htdocs...')
#3 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-05-15 14:25:27 --> Error connecting to the database: Uninitialized string offset: 0
CRITICAL - 2021-05-15 14:25:27 --> Unable to connect to the database.
#0 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `orders`...', Array, false)
#2 D:\xampp\htdocs\diancan\app\Models\Orders_model.php(514): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\diancan\app\Controllers\Admin\Dashboard.php(15): App\Models\Orders_model->getOrdersCountGroupByRegion()
#4 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(876): App\Controllers\Admin\Dashboard->index()
#5 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(411): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Dashboard))
#6 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(322): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\diancan\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2021-05-15 14:25:52 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2021-05-15 14:25:52 --> Unable to connect to the database.
#0 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `orders`...', Array, false)
#2 D:\xampp\htdocs\diancan\app\Models\Orders_model.php(514): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\diancan\app\Controllers\Admin\Dashboard.php(15): App\Models\Orders_model->getOrdersCountGroupByRegion()
#4 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(876): App\Controllers\Admin\Dashboard->index()
#5 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(411): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Dashboard))
#6 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(322): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\diancan\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-05-15 14:25:52 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\xampp\\htdocs...', 100, Array)
#1 D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Admin\Dashboard), true)
#2 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('D:\\xampp\\htdocs...')
#3 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-05-15 14:35:35 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2021-05-15 14:35:35 --> Unable to connect to the database.
#0 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `orders`...', Array, false)
#2 D:\xampp\htdocs\diancan\app\Models\Orders_model.php(514): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\diancan\app\Controllers\Admin\Dashboard.php(15): App\Models\Orders_model->getOrdersCountGroupByRegion()
#4 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(876): App\Controllers\Admin\Dashboard->index()
#5 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(411): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Dashboard))
#6 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(322): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\diancan\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-05-15 14:35:35 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\xampp\\htdocs...', 100, Array)
#1 D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Admin\Dashboard), true)
#2 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('D:\\xampp\\htdocs...')
#3 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-05-15 14:35:57 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2021-05-15 14:35:57 --> Unable to connect to the database.
#0 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT `orders`...', Array, false)
#2 D:\xampp\htdocs\diancan\app\Models\Orders_model.php(514): CodeIgniter\Database\BaseBuilder->get()
#3 D:\xampp\htdocs\diancan\app\Controllers\Admin\Dashboard.php(15): App\Models\Orders_model->getOrdersCountGroupByRegion()
#4 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(876): App\Controllers\Admin\Dashboard->index()
#5 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(411): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\Dashboard))
#6 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\CodeIgniter.php(322): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 D:\xampp\htdocs\diancan\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2021-05-15 14:35:57 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'D:\\xampp\\htdocs...', 100, Array)
#1 D:\xampp\htdocs\diancan\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Admin\Dashboard), true)
#2 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('D:\\xampp\\htdocs...')
#3 D:\xampp\htdocs\diancan\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
